# Generated by Django 4.1.5 on 2023-03-30 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='module_image',
            field=models.ImageField(blank=True, null=True, upload_to='modules/'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_imgs',
            field=models.ImageField(blank=True, null=True, upload_to='lessons/imgs'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_notes',
            field=models.FileField(blank=True, null=True, upload_to='lesson/notes'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_vid',
            field=models.FileField(blank=True, null=True, upload_to='lesson/video'),
        ),
        migrations.AlterField(
            model_name='program',
            name='program_image',
            field=models.ImageField(blank=True, null=True, upload_to='prorams/'),
        ),
    ]
